# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0008_auto_20170605_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeinfo',
            name='prev_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tradeinfo_preclub', to='introduction_to_models.Club'),
        ),
        migrations.AddField(
            model_name='tradeinfo',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tradeinfo_invites', to='introduction_to_models.Player'),
        ),
    ]
