# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0018_auto_20170607_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('students', models.ManyToManyField(to='introduction_to_models.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
