# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0019_lecturee_studente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='lecturee',
            name='students',
        ),
        migrations.DeleteModel(
            name='Studente',
        ),
        migrations.AddField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(related_name='like_posts', to='introduction_to_models.User'),
        ),
        migrations.DeleteModel(
            name='Lecturee',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='introduction_to_models.Tag'),
        ),
    ]
